export const api = {
    'email_request_custom': 'email/request/custom',
    'email_handle_request_custom': 'email/handle/request/custom',
    'email_country': 'email/country',
    'manage_email': 'manage',
    'manage_email_get_total': 'manage/total',
    'manage_email_send_now': 'action/send',
    'manage_email_send_now_again': 'action/send/again',
    'manage_email_stop_email': 'action/stop',
    'manage_email_delete_email': 'action/delete',
    'manage_email_block_user': 'action/user/block',
    'manage_email_get_product_list': 'action/product/list',
    'manage_email_block_product': 'action/product/block',
    'manage_email_bulk_send_now': 'bulk/send',
    'manage_email_bulk_send_now_all': 'bulk/send/all',
    'manage_email_bulk_stop_email': 'bulk/stop',
    'manage_email_bulk_stop_email_all': 'bulk/stop/all',
    'manage_email_bulk_delete_email': 'bulk/delete',
    'manage_email_bulk_delete_email_all': 'bulk/delete/all',
    'manage_email_check_welcome': 'manage/welcome',
    'email_reset_setting': 'email/reset/setting',
    'email_using_email': 'email/using/email',
    'manage_email_get_product_blacklist': 'blacklist/product',
    'email_blacklist': 'email/blacklist',
    'product_blacklist': 'email/product/blacklist',
    'email_product': 'email/product',
    'email_customer': 'email/customer',
    'send_email_test': 'schedule/test',
    'email_summary' : 'manage/summary',
    'theme_setting': 'v4_5/settings/theme',
    'theme_setting_reset': 'v4_5/settings/theme/reset',
    'theme_setting_version': 'v4_5/settings/theme/version',
    'theme_setting_upgrade': 'v4_5/settings/theme/upgrade',
    'theme_setting_check_contact' : 'v4_5/settings/theme/check-contact',
    'theme_setting_close_contact' : 'v4_5/settings/theme/close-contact',
    'popup_reviews_theme_Settings': 'popup-reviews/api/themeSettings',
    'popup_reviews_reset_theme_settings': 'popup-reviews/api/themeSettingsReset',
    'popup_reviews_api_display_rule_settings': 'popup-reviews/api/displayRuleSettings',
    'popup_reviews_api_page_rule_settings': 'popup-reviews/api/pageRuleSettings',
    'popup_reviews_api_search_products': 'popup-reviews/api/searchProduct',
    'popup_reviews_api_products_specific': 'popup-reviews/api/productsSpecific',
    'popup_reviews_api_collections': 'popup-reviews/api/collections',
    'popup_reviews_api_collection_specific': 'popup-reviews/api/collectionSpecific',
    'popup_reviews_api_combo': 'popup-reviews/api/combo',
    'popup_reviews_api_excluded_products': 'popup-reviews/api/excludedProducts',
    'popup_reviews_api_display_rule_settings_reset': 'popup-reviews/api/displayRuleSettingsReset',
    'widget_themes_setting': 'settings/widget-themes-setting',
    'settings_import_csv': 'settings-import-csv',
    'csv_processing': 'csv/processing',
    'tracking_type_import': 'api/tracking-type-import',
    'setting_auto_publish_reviews': 'settings/get-setting-auto-publish-reviews',
    'auto_update_review_get_settings_auto_update': 'auto-update-review/get-settings-auto-update',
    'auto_update_review_settings_auto_update_reviews': 'auto-update-review/settings-auto-update-reviews',
    'auto_update_review_settings_per_product_get_reviews': 'auto-update-review/settings-per-product-get-reviews',
    'auto_update_review_list_auto_update_products': 'auto-update-review/list-auto-update-products',
    'auto_update_review_update_link_aliexpress_from_auto_update': 'auto-update-review/update-link-aliexpress-from-auto-update',
    'auto_update_review_reset_settings_auto_update_reviews': 'auto-update-review/reset-settings-auto-update-reviews',
    'auto_update_review_list_products_run_auto_update': 'auto-update-review/list-products-run-auto-update',
    'auto_update_review_post_settings_per_product_get_reviews': 'auto-update-review/settings-per-product-get-reviews',
    'auto_update_review_get_settings_per_product_get_reviews': 'auto-update-review/get-settings-per-product-get-reviews',
    'auto_update_review_reset_multi_action_setting_per_product': 'auto-update-review/reset-multi-action-setting-per-product',
    'auto_update_review_save_firstime_auto_update': 'auto-update-review/save-firstime-auto-update',
    'google_shopping_get_setting_product_rating': 'google-shopping/get-setting-product-rating',
    'google_shopping_all_product_use_product_rating': 'google-shopping/all-product-use-product-rating',
    'google_shopping_update_setting_product_rating': 'google-shopping/update-setting-product-rating',
    'google_shopping_save_firstime_google_shopping' : 'google-shopping/save-firstime-google-shopping',
    'google_shopping_reset_settings_auto_product_rating' : 'google-shopping/reset-settings-auto-product-rating',
    'google_shopping_check_file_google_shopping' : 'google-shopping/check-file-google-shopping'
}
